package practice.strings.strings;

import org.junit.jupiter.api.Test;

public class StringConcepts {


    @Test
        void CheckStringPool(){

        String str1= "Hello";
        String str2= "Hello";

        String str3="He";
        String str4= str3+"llo";
        final String str5= "He";
        String str6= str5 +"llo";

        System.out.println("str1 == str2 ?" +(str1==str2));
        System.out.println("str1 == str4 ?" +(str1==str4));
        System.out.println("str1 == str6 ?" +(str1==str6));

        str4=str4.intern();
        System.out.println("str1 == str4 ?" +(str1==str4));

    }

    @Test
        void commentsCheck1(){
        /**
         * This example contains \ u without space and causes compile error. removed for loading purpose.
         * Generated by the IBM IDL-to-Java compiler, version 1.0
         * from F:\TestRoot\apps\a1\ units\include\PolicyHome.idl
         * Wednesday, June 17, 1998 6:44:40 o'clock Am GMT+00:00
         */
                System.out.print("Hell");
                System.out.println("o world");

    }




}
